codecov:
  url: "http://192.241.135.241"

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project: no
    patch: no

comment:
  layout: header, diff, changes, sunburst, uncovered, tree
  behavior: default
  require_changes: no
